[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer=true
optimizer_runs=1000000

[dependencies]
solmate = "6.8.0"
"@account-abstraction" = { version = "0.8.0", url = "https://github.com/eth-infinitism/account-abstraction/archive/refs/tags/v0.8.0.zip" }
"@openzeppelin-contracts" = "5.3.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
